AmruthaCollege/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('collegeapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

collegeapp/urls.py
from django.urls import path
from .import views
app_name ='collegeapp'


urlpatterns = [
    path('',views.index,name="index"),
    path('home/',views.home,name="home"),
    path('formss/',views.formss,name="formss"),
   
    path('register/',views.register,name="register"),
    
    path('register_student/',views.register_student,name="register_student"),
    
    path('login/',views.login,name="login"),
    path('login_student/',views.login_student,name="login_student"),
    
    # path('form/',views.regforms,name="regforms"),
    # path('form_student/',views.form_student,name="form_student"),
   
    
    # path('register/',views.register,name="register"),
    
    
    
   
     
   
    
]

collegeapp/models.py
from django.db import models

# Create your models here.

class department(models.Model):
    name=models.CharField(max_length=225)

    def __str__(self):
        return self.name
class course(models.Model):
    name=models.CharField(max_length=225)
    department=models.ForeignKey(department,on_delete=models.CASCADE) 

    def __str__(self):
        return self.name   

class studentdetails(models.Model):
    name=models.CharField(max_length=255)
    Dob=models.CharField(max_length=255)
    age=models.IntegerField(blank=True,null=True)
    gender=models.CharField(max_length=255)
    phonenumber=models.CharField(max_length=255)
    email=models.EmailField(max_length=255)
    address=models.CharField(max_length=255)
    purpose=models.CharField(max_length=255,blank=True,null=True)
    course=models.ForeignKey(course,on_delete=models.SET_NULL, blank=True, null=True)
    department=models.ForeignKey(department,on_delete=models.SET_NULL, blank=True, null=True)
    
    def __str__(self):
        return self.name  
    
    
    
# from django.db import models


# class Country(models.Model):
#     name = models.CharField(max_length=40)

#     def __str__(self):
#         return self.name


# class City(models.Model):
#     country = models.ForeignKey(Country, on_delete=models.CASCADE)
#     name = models.CharField(max_length=40)

#     def __str__(self):
#         return self.name


# class Person(models.Model):
#     name = models.CharField(max_length=124)
#     country = models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True)
#     city = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True)

#     def __str__(self):
#         return self.name    

collegeapp/forms.py
from django import forms

from collegeapp.models import studentdetails, course


class StudentCreationForm(forms.ModelForm):
    class Meta:
        model = studentdetails
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset =course.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['course'].queryset = course.objects.filter(department_id = department_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['course'].queryset = self.instance.country.city_set.order_by('name')

collegeapp/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User

from django.shortcuts import render,redirect
from django.contrib.auth.models import User,auth


from collegeapp.models import*

# Create your views here.
def index(request):
    return render(request, 'index.html')

def login(request):
    return render(request, 'login.html')

def register(request):
    return render(request, 'Register.html')

def home(request):
    return render(request,'Home.html')
def formss(request):
    return render(request,'formss.html')

# def regforms(request):
#     return render(request,'form.html')



# def register_student(request):
#     if request.method == 'POST':
#         print("Register")
      
            
#         username=request.POST["username"]
        
#         password=request.POST["password"]
#         cpassword=request.POST["cpassword"]
#         if password==cpassword:
#             if User.objects.filter(username=username).exists():
#                 messages.info(request,"username taken")
#                 return redirect("register_student")
           
#             else:
                
#                 user=User.objects.create_user(username=username,password=password)
#                 user.save()
#                 return render(request,'login.html')
#                 print("created")
#         else:
#             messages.info(request,'password not matching')
#             return redirect("register_student")
#         return redirect("login" )  
#     else:    
#         return render(request,'Register.html')
def register_student(request):
    if request.method == 'POST':
        username = request.POST['username']
        # first_name = request.POST['first_name']
        # last_name = request.POST['last_name']
        # email = request.POST['email']
        password = request.POST['password']
        password1 = request.POST['cpassword']
        if password == password1:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'username taken ')
                # return redirect('register')
            # elif User.objects.filter(email=email).exists():
            #     messages.info(request, 'email taken ')
                return redirect('register_student')
            else:
                user = User.objects.create_user(username=username, 
                                                password=password, )
                user.save();
            return redirect('login_student')

        else:
            messages.info(request, 'password not matching')
            return redirect('register_student')
        return redirect('/')
    return render(request,'Register.html')    


def login_student(request):
    if request.method=="POST":    
        username=request.POST["username"]
        password=request.POST["password"]
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return render(request,"Home.html")
        
        else:
            messages.info(request,"User name or password incorrect")
            return redirect('login_student')
            
        
    return render(request,'login.html')

def form_student(request):
    cose= course.objects.all()
    dep=department.objects.all()
    if request.method=="POST": 
        name=request.POST["fullname"]
        Dob=request.POST["date"]
        age=request.POST["age"]
        
        gender=request.POST["gender"]
        phnumber=request.POST["number"]
        email=request.POST["email"]
        deptm=request.POST['dept']
        cour=request.POST['coses']
        address=request.POST["address"]
        purpose=request.POST["purpose"]
        
        dep=department.objects.all()  
        print(dep)
        cose=department.objects.get(id=cour)  
        details=studentdetails (department=dep,course=cose,name=name,Dob=Dob,age=age,gender=gender,phonenumber=phnumber,email=email,address=address,purpose=purpose) 
        details.save()
        
        return redirect('form_student')
    return render(request,'form.html',{'dep':dep,'cose':cose})
        
    
     

templates/Register.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">


        <!-- Font Awesome -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
rel="stylesheet"
/>
<!-- Google Fonts -->
<link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/>
<!-- MDB -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.1/mdb.min.css"
rel="stylesheet"
/>


<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title> Toronto University</title>

<link rel="shortcut icon" href="{% static 'assets/images/fav.jpg' %}">
<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/fontawsom-all.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/plugins/slider/css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/plugins/slider/css/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}" />
<link rel="stylesheet" href="{% static 'https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css' %}" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">










    </head>
    <body>

      <header>
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-12 left-item">
                        <ul>
                            <li><i class="fas fa-envelope-square"></i> sales@smarteyeapps.com</li>
                            <li><i class="fas fa-phone-square"></i> +123 987 887 765</li>
                        </ul>
                    </div>
                    <div class="col-lg-5 d-none d-lg-block right-item">
                        <ul>
                            <li><a><i class="fab fa-github"></i></a></li>
                            <li><a><i class="fab fa-google-plus-g"></i></a></li>
                            <li> <a><i class="fab fa-pinterest-p"></i></a></li>
                            <li><a><i class="fab fa-twitter"></i></a></li>
                            <li> <a><i class="fab fa-facebook-f"></i></a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <div id="nav-head" class="header-nav">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-12 nav-img">
                        <img src="{% static 'assets/images/logo.png'%}" alt="">
                       <a data-toggle="collapse" data-target="#menu" href="#menu" ><i class="fas d-block d-md-none small-menu fa-bars"></i></a>
                    </div>
                    <div id="menu" class="col-md-9 d-none d-md-block nav-item">
                        <ul>
                            <li><a href="{% url 'collegeapp:index' %}">HOME</li></a>
                            <li><a href="{% url 'collegeapp:login' %}">LOGIN</li></a>
                            <li> <a href="{% url 'collegeapp:register' %}">REGISTER</li></a>
                           {% comment %} <li><a href="cources.html">DEPARTMENT</a></li>  {% endcomment %}
                            {% comment %} <li><a href="blog.html">Blog</a></li>
                            <li><a href="gallery.html">Gallery</a></li>
                            <li><a href="contact_us.html">Contact Us</a></li> {% endcomment %}
                        </ul>
                        {% comment %} <div class="dropdown">
                            <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              DEPARTMENT
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Mechanical_engineering">MECHANICAL</a>
                              <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Electrical_engineering">ELECTRICAL</a>
                              <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Electronics">ELECTRONICS</a>
                              <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">COMMERCE</a>
                              <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">COMPUTER SCIENCE</a>
                            </div>
                          </div> {% endcomment %}
                    </div>
                </div>

            </div>
        </div>

    </header>
       








<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">REGISTER</p>
  
                  <form class="mx-1 mx-md-4" action="{% url 'collegeapp:register' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="text" name="username" id="form3Example1c" class="form-control" />
                        <label class="form-label" for="form3Example1c">User Name</label>
                      </div>
                    </div>
  
                    {% comment %} <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="email" id="form3Example3c" class="form-control" />
                        <label class="form-label" for="form3Example3c">Your Email</label>
                      </div>
                    </div> {% endcomment %}
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="password" name="password" id="form3Example4c" class="form-control" />
                        <label class="form-label" for="form3Example4c">Password</label>
                      </div>
                    </div>
  
                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                        <input type="password" name="cpassword" id="form3Example4cd" class="form-control" />
                        <label class="form-label" for="form3Example4cd">Confirm password</label>
                      </div>
                    </div>
  
                    {% comment %} <div class="form-check d-flex justify-content-center mb-5">
                      <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" />
                      <label class="form-check-label" for="form2Example3">
                        I agree all statements in <a href="#!">Terms of service</a>
                      </label>
                    </div> {% endcomment %}
                    
                    {% comment %} <form method="get" action="{% url 'collegeapp:login_student' %}">
                      <input type="submit">
                    </form>
   {% endcomment %}
                     <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <input type="submit"  value="Register" class="form-control w-50 btn btn-info"><br>
                     
                    </div> 
                    Already registered?  <a href="{% url 'collegeapp:login_student' %}">login</a></button>
  
                  </form>
                  
                  <h2>{% for msg in messages %}</h2>
                  {{  msg }}
                  {% endfor %}
  
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
  
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


  <script
type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.1/mdb.min.js"
></script>

          
  <script src="" async defer></script>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
<!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.1/mdb.min.css"
  rel="stylesheet"
/>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title> Toronto University</title>

<link rel="shortcut icon" href="{% static 'assets/images/fav.jpg' %}">
<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/fontawsom-all.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/plugins/slider/css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/plugins/slider/css/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}" />
<link rel="stylesheet" href="{% static 'https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css' %}" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">









    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
 
        <header>
          <div class="header-top">
              <div class="container">
                  <div class="row">
                      <div class="col-lg-7 col-md-12 left-item">
                          <ul>
                              <li><i class="fas fa-envelope-square"></i> sales@smarteyeapps.com</li>
                              <li><i class="fas fa-phone-square"></i> +123 987 887 765</li>
                          </ul>
                      </div>
                      <div class="col-lg-5 d-none d-lg-block right-item">
                          <ul>
                              <li><a><i class="fab fa-github"></i></a></li>
                              <li><a><i class="fab fa-google-plus-g"></i></a></li>
                              <li> <a><i class="fab fa-pinterest-p"></i></a></li>
                              <li><a><i class="fab fa-twitter"></i></a></li>
                              <li> <a><i class="fab fa-facebook-f"></i></a></li>
                          </ul>
                      </div>
                  </div>
  
              </div>
          </div>
          <div id="nav-head" class="header-nav">
              <div class="container">
                  <div class="row">
                      <div class="col-md-3 col-sm-12 nav-img">
                          <img src="{% static 'assets/images/logo.png'%}" alt="">
                         <a data-toggle="collapse" data-target="#menu" href="#menu" ><i class="fas d-block d-md-none small-menu fa-bars"></i></a>
                      </div>
                      <div id="menu" class="col-md-9 d-none d-md-block nav-item">
                          <ul>
                              <li><a href="{% url 'collegeapp:index' %}">HOME</li></a>
                              <li><a href="{% url 'collegeapp:login' %}">LOGIN</li></a>
                              <li> <a href="{% url 'collegeapp:register' %}">REGISTER</li></a>
                             {% comment %} <li><a href="cources.html">DEPARTMENT</a></li>  {% endcomment %}
                              {% comment %} <li><a href="blog.html">Blog</a></li>
                              <li><a href="gallery.html">Gallery</a></li>
                              <li><a href="contact_us.html">Contact Us</a></li> {% endcomment %}
                          </ul>
                          {% comment %} <div class="dropdown">
                              <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                DEPARTMENT
                              </button>
                              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Mechanical_engineering">MECHANICAL</a>
                                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Electrical_engineering">ELECTRICAL</a>
                                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Electronics">ELECTRONICS</a>
                                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">COMMERCE</a>
                                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">COMPUTER SCIENCE</a>
                              </div>
                            </div> {% endcomment %}
                      </div>
                  </div>
  
              </div>
          </div>
  
      </header>


<section class="h-100 gradient-form" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
          <div class="card rounded-3 text-black">
            <div class="row g-0">
              <div class="col-lg-6">
                <div class="card-body p-md-5 mx-md-4">
  
                  <div class="text-center">
                    <img src="{% static 'assets/images/logo.png'%}"
                      style="width: 185px;" alt="logo">
                    <h4 class="mt-1 mb-5 pb-1">We are The Education Team</h4>
                  </div>
  
                  <form class="mx-1 mx-md-4" action="{% url 'collegeapp:login_student' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Please login to your account</p>

                    
                  <input type="text" name="username" placeholder="Username" class="form-control w-50"><br>
                  
                  <input type="password" name="password" placeholder="Password" class="form-control w-50"><br>
  
                    {% comment %} <div class="form-outline mb-4">
                      <input type="email" name="username" id="form2Example11" class="form-control"
                       
                      <label class="form-label" for="form2Example11">Username</label>
                    </div>
  
                    <div class="form-outline mb-4">
                      <input type="password" name="password" id="form2Example22" class="form-control" />
                      <label class="form-label" for="form2Example22">Password</label>
                    </div> {% endcomment %}
  
                    {% comment %} <div class="text-center pt-1 mb-5 pb-1">
                      <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="button">Log
                        in</button>
                      <a class="text-muted" href="#!">Forgot password?</a>
                    </div> {% endcomment %}
  
                    {% comment %} <div class="d-flex align-items-center justify-content-center pb-4">
                      <p class="mb-0 me-2">Don't have an account?</p>
                      <button type="button" class="btn btn-outline-danger">Create new</button>
                    </div> {% endcomment %}

                   <input type="submit"  value="Log in" class="form-control w-50 btn btn-info"><br>
                    Dont have an account? <a href="{% url 'collegeapp:register' %}">Register</a>


                   

                 

  
                  </form>
                  <div>
                    {% for message in messages %}
                    <h5>
                        <div class="alert alert-danger mt-5">
                          <b><h1 style='color:red' class='font-danger'>  {{ message }}</b></h1>
                        </div>
                    </h5>
                        {% endfor %}
                </div>
  
                </div>
                {% comment %} {% for message in messages %}
                <h5>
                    <div class="alert alert-danger mt-5">
                      <b><h1 style='color:red' class='font-danger'>  {{ message }}</b></h1>
                    </div>
                </h5>
                    {% endfor %}  {% endcomment %}


              </div>
              <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                  <h4 class="mb-4">We are more than just a University</h4>
                  <p class="small mb-0">The University of Toronto offers over 700 undergraduate and 200 graduate programs. The university receives the most annual scientific research funding and endowment of any Canadian university and is one of two members of the Association of American Universities outside the United States, alongside McGill University. Academically, the University of Toronto is noted for influential movements and curricula in literary criticism and communication theory, known collectively as the Toronto School. It is the largest university in Canada in terms of enrolment with more than 97,000 students</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <style>


    .gradient-custom-2 {
        /* fallback for old browsers */
        background: #fccb90;
        
        /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
        
        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
        }
        
        @media (min-width: 768px) {
        .gradient-form {
        height: 100vh !important;
        }
        }
        @media (min-width: 769px) {
        .gradient-custom-2 {
        border-top-right-radius: .3rem;
        border-bottom-right-radius: .3rem;
        }
        }




  </style>

  <!-- MDB -->
<script
type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.1/mdb.min.js"
></script>


  <script src="" async defer></script>
</body>
</html>